[package]
name = "file-header"
version = "0.1.0"
publish = true
edition = "2021"

[dependencies]
thiserror = "1.0.44"
crossbeam = "0.8.2"
walkdir = "2.3.3"
lazy_static = { version = "1.4.0", optional = true }
license = { version = "3.1.1", optional = true }

[dev-dependencies]
tempfile = "3.7.0"
globset = "0.4.11"

[features]
default = ["spdx"]
spdx = ["dep:license", "dep:lazy_static"]
